# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: detect-private-key
    -   id: check-ast

-   repo: 'https://github.com/PyCQA/flake8'
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-print
          - pep8-naming
          - flake8-docstrings
          - flake8-requirements
-   repo: 'https://github.com/psf/black'
    rev: 24.2.0
    hooks:
    -   id: black
        exclude: migrations/
-   repo: 'https://github.com/PyCQA/isort'
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black"]
        name: isort (python)
    -   id: isort
        name: isort (cython)
        types: [cython]
    -   id: isort
        name: isort (pyi)
        types: [pyi]
-   repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.910
    hooks:
    - id: mypy
-   repo: local
    hooks:
    -   id: run-tests
        name: Run tests
        description: Runs unittest discover to run Python based unit tests
        types: [python]
        language: system
        pass_filenames: false
        entry: python -m unittest discover -qb
        stages: [commit]
